// <auto-generated />
using System;
using Day18.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Day18.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260509092509_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Day18.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BookingTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MovieId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MovieTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("Day18.Models.ChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SenderRole")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("Day18.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("HallNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PosterColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ShowDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Продолжение эпической истории о мире Пандоры",
                            Duration = 192,
                            Genre = "Фантастика",
                            HallNumber = 1,
                            PosterColor = "#FF1565C0",
                            ShowDate = new DateTime(2026, 5, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            Time = "10:00",
                            Title = "Аватар 2"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Яркая комедия о кукле Барби в реальном мире",
                            Duration = 114,
                            Genre = "Комедия",
                            HallNumber = 1,
                            PosterColor = "#FFE91E63",
                            ShowDate = new DateTime(2026, 5, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            Time = "12:30",
                            Title = "Барби"
                        },
                        new
                        {
                            Id = 3,
                            Description = "История создателя атомной бомбы",
                            Duration = 180,
                            Genre = "Драма",
                            HallNumber = 2,
                            PosterColor = "#FF424242",
                            ShowDate = new DateTime(2026, 5, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            Time = "15:45",
                            Title = "Оппенгеймер"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Новые приключения легендарного киллера",
                            Duration = 169,
                            Genre = "Боевик",
                            HallNumber = 2,
                            PosterColor = "#FF7B1FA2",
                            ShowDate = new DateTime(2026, 5, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            Time = "19:00",
                            Title = "Джон Уик 4"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Продолжение эпической саги о пустынной планете",
                            Duration = 166,
                            Genre = "Фантастика",
                            HallNumber = 3,
                            PosterColor = "#FFF9A825",
                            ShowDate = new DateTime(2026, 5, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            Time = "21:30",
                            Title = "Дюна 2"
                        });
                });

            modelBuilder.Entity("Day18.Models.NotificationModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Day18.Models.Seat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BookingId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MovieId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Row")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Seats");
                });

            modelBuilder.Entity("Day18.Models.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AvailableSeats")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HallNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MovieGenre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MovieTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("TicketPrice")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Sessions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailableSeats = 100,
                            Duration = 192,
                            HallNumber = 1,
                            MovieGenre = "Фантастика",
                            MovieTitle = "Аватар 2",
                            StartTime = new DateTime(2026, 5, 9, 10, 0, 0, 0, DateTimeKind.Local),
                            TicketPrice = 25,
                            TotalSeats = 100
                        },
                        new
                        {
                            Id = 2,
                            AvailableSeats = 100,
                            Duration = 114,
                            HallNumber = 1,
                            MovieGenre = "Комедия",
                            MovieTitle = "Барби",
                            StartTime = new DateTime(2026, 5, 9, 13, 0, 0, 0, DateTimeKind.Local),
                            TicketPrice = 20,
                            TotalSeats = 100
                        },
                        new
                        {
                            Id = 3,
                            AvailableSeats = 120,
                            Duration = 180,
                            HallNumber = 2,
                            MovieGenre = "Драма",
                            MovieTitle = "Оппенгеймер",
                            StartTime = new DateTime(2026, 5, 9, 16, 0, 0, 0, DateTimeKind.Local),
                            TicketPrice = 28,
                            TotalSeats = 120
                        },
                        new
                        {
                            Id = 4,
                            AvailableSeats = 120,
                            Duration = 169,
                            HallNumber = 2,
                            MovieGenre = "Боевик",
                            MovieTitle = "Джон Уик 4",
                            StartTime = new DateTime(2026, 5, 9, 19, 0, 0, 0, DateTimeKind.Local),
                            TicketPrice = 25,
                            TotalSeats = 120
                        },
                        new
                        {
                            Id = 5,
                            AvailableSeats = 80,
                            Duration = 166,
                            HallNumber = 3,
                            MovieGenre = "Фантастика",
                            MovieTitle = "Дюна 2",
                            StartTime = new DateTime(2026, 5, 9, 21, 0, 0, 0, DateTimeKind.Local),
                            TicketPrice = 30,
                            TotalSeats = 80
                        });
                });

            modelBuilder.Entity("Day18.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BookingTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MovieTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SessionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SessionTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("Day18.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Администратор",
                            PasswordHash = "JAvlGPq9JyTdtvBO6x2llnRI1+gxwIyPqCKAn3THIKk=",
                            PhoneNumber = "+375 (29) 123-45-67",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Иван Петров",
                            PasswordHash = "5gbjiw2MGbJM8O44CBgxYup81j/3kS27IrXoAyhrREY=",
                            PhoneNumber = "+375 (33) 987-65-43",
                            Role = "User",
                            Username = "user"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
